//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("ChilliSource Mobile Core")]
[assembly: AssemblyVersion("1.0.2")]
[assembly: AssemblyFileVersion("1.0.2")]
[assembly: AssemblyInformationalVersion("1.0.2-alpha.4+Branch.develop.Sha.a8c9fe6ae979572f90b299e456c408d62ab88d49")]
[assembly: AssemblyCopyright("Copyright Blue Chilli Technology Pty Ltd 2017")]

